"""Train the CP4 within-tier MRR-weighted pairwise reranker.

Protocol (prompt_cp4 Task 3):

- Groups are generated by replaying sessions against the current agent with
  full tier dominance, so training pairs exist only WITHIN dominance tiers —
  exactly the ordering decision the runtime delegates to the learned score.
- Each pair (target, same-tier negative) is weighted by the reciprocal-rank
  change it could cause under the reference (CP3) ranking, with extra weight
  when the pair crosses the top-10 boundary. Public-session pairs are
  upweighted.
- Training data: public dev 150 + synthetic_train 3000. Selection: mean of
  public five-fold out-of-fold TechnicalScore and synthetic_dev
  TechnicalScore, evaluated statically with the dominance rank rule
  (global rank = higher-tier count + within-tier rank).
- Candidate features beyond the 16 CP3 features are kept only if the
  selection folds show gains; every candidate is reported either way.

Requires numpy and scikit-learn (training only; the runtime stays stdlib).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pickle
from collections import defaultdict
from pathlib import Path

try:
    import numpy as np
    from sklearn.linear_model import LogisticRegression
except ImportError as error:  # pragma: no cover - optional training dependency
    raise SystemExit(
        "Training requires numpy and scikit-learn. Runtime inference does not."
    ) from error

from evaluator.local_evaluator import (
    MAX_TURNS,
    catalog_index,
    coarse_category,
    customer_reply,
    initial_message,
    load_jsonl,
    materialize_hidden_fields,
    metric_summary,
)
from starter.agent import Agent, RERANK_FEATURE_NAMES


C_GRID = (0.01, 0.05, 0.1, 0.5, 1.0)
BASE_FEATURES = tuple(range(16))
EXTRA_FEATURES = {name: index for index, name in enumerate(RERANK_FEATURE_NAMES)}


def technical_score(sessions: list[dict]) -> dict:
    summary = metric_summary(sessions)
    efficiency = max(0.0, min(1.0, (11.0 - float(summary["mttc"])) / 10.0))
    score = 0.5 * summary["hit_rate_at_10"] + 0.3 * summary["mrr"] + 0.2 * efficiency
    return {
        **summary,
        "efficiency": round(efficiency, 6),
        "recommended_technical_score": round(score, 6),
    }


def generate_groups(agent: Agent, samples: list[dict], categories, products, partition: str) -> list[dict]:
    """Replay sessions and capture the target's dominance tier per new state."""
    groups: list[dict] = []
    for sample in samples:
        sample_id = str(sample["sample_id"])
        target = str(sample["ground_truth"]["parent_asin"])
        intent_card, behavior = materialize_hidden_fields(sample, products)
        effective = {**sample, "intent_card": intent_card, "behavior": behavior}
        session_id = f"cp4_train_{partition}_{sample_id}"
        agent.reset(session_id, sample["user_profile"])
        disclosed: set[str] = set()
        boundary_used = False
        override_applied = sample["scenario_type"] != "intent_override"
        user_message = initial_message(
            effective, coarse_category(categories.get(target, [])), disclosed
        )
        seen_states: set[tuple[str, ...]] = set()
        for turn in range(1, MAX_TURNS + 1):
            response = agent.respond(session_id, user_message, turn, 10)
            state = agent._sessions[session_id]
            query_terms = [str(value) for value in state.get("last_query_terms", [])]
            signature = tuple(query_terms)
            if override_applied and signature not in seen_states:
                seen_states.add(signature)
                pool = [str(value) for value in state.get("last_candidates", [])]
                messages = state["messages"]
                query_text = (
                    " ".join(str(item) for item in messages)
                    if isinstance(messages, list) else ""
                )
                constraints = agent._constraint_phrases(messages)
                _, counts = agent._exact_evidence_pool(constraints)
                group = {
                    "sample_id": sample_id,
                    "partition": partition,
                    "scenario": str(sample["scenario_type"]),
                    "turn": turn,
                }
                if target not in pool:
                    group["absent"] = True
                    groups.append(group)
                else:
                    target_count = counts.get(target, 0) if counts else 0
                    if counts:
                        tier = [
                            asin for asin in pool
                            if counts.get(asin, 0) == target_count
                        ]
                        n_higher = sum(
                            1 for asin in pool if counts.get(asin, 0) > target_count
                        )
                    else:
                        tier = pool
                        n_higher = 0
                    pool_rank = {asin: rank for rank, asin in enumerate(pool, start=1)}
                    matrix = np.asarray([
                        agent._feature_vector(
                            asin, pool_rank[asin], state, query_terms,
                            constraints, query_text,
                        )
                        for asin in tier
                    ], dtype=np.float32)
                    group.update({
                        "absent": False,
                        "n_higher": int(n_higher),
                        "matrix": matrix,
                        "pool_ranks": np.asarray(
                            [pool_rank[asin] for asin in tier], dtype=np.int32
                        ),
                        "target_index": tier.index(target),
                    })
                    groups.append(group)
            if turn == MAX_TURNS:
                break
            override = effective.get("behavior", {}).get("override") or {}
            if not override_applied and turn + 1 == int(override.get("turn", 3)):
                override_applied = True
                new_value = str(override.get("new_value", ""))
                if new_value:
                    disclosed.add(new_value)
                user_message = str(
                    override.get("message", "Actually, please ignore my earlier preference.")
                )
            else:
                user_message, boundary_used = customer_reply(
                    effective, response.get("ask_attribute"), disclosed, boundary_used
                )
    return groups


def tier_ranks(matrix: np.ndarray, pool_ranks: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """One-based within-tier ranks under weights, tie-broken by pool rank."""
    scores = matrix @ weights
    order = np.lexsort((pool_ranks, -scores))
    ranks = np.empty(len(order), dtype=np.int64)
    ranks[order] = np.arange(1, len(order) + 1)
    return ranks


def build_pairs(
    groups: list[dict],
    reference: np.ndarray,
    pairs_per_group: int,
    boundary_boost: float,
    public_weight: float,
) -> dict:
    rows: list[np.ndarray] = []
    labels: list[int] = []
    weights: list[float] = []
    pair_sample_ids: list[str] = []
    flip = False
    for group in groups:
        if group.get("absent") or len(group.get("matrix", ())) < 2:
            continue
        matrix = group["matrix"].astype(np.float64)
        ranks = group["n_higher"] + tier_ranks(matrix, group["pool_ranks"], reference)
        target_index = group["target_index"]
        target_rank = ranks[target_index]
        pair_weights = np.abs(1.0 / target_rank - 1.0 / ranks)
        crossing = (ranks <= 10) != (target_rank <= 10)
        pair_weights = pair_weights * np.where(crossing, boundary_boost, 1.0)
        if group["partition"] == "public":
            pair_weights = pair_weights * public_weight
        pair_weights[target_index] = 0.0
        keep = np.argsort(-pair_weights)[:pairs_per_group]
        keep = keep[pair_weights[keep] > 0.0]
        positive = matrix[target_index]
        for index in keep:
            difference = positive - matrix[index]
            if flip:
                rows.append(-difference)
                labels.append(0)
            else:
                rows.append(difference)
                labels.append(1)
            flip = not flip
            weights.append(float(pair_weights[index]))
            pair_sample_ids.append(group["sample_id"])
    if not rows:
        raise ValueError("no pairs generated")
    weight_array = np.asarray(weights, dtype=np.float64)
    weight_array /= weight_array.mean()
    return {
        "X": np.vstack(rows),
        "y": np.asarray(labels, dtype=np.int8),
        "w": weight_array,
        "sample_ids": np.asarray(pair_sample_ids, dtype=object),
    }


def fit_weights(pairs: dict, mask: tuple[int, ...], regularization: float,
                exclude_sample_ids: set[str] | None = None) -> np.ndarray:
    selector = np.ones(len(pairs["y"]), dtype=bool)
    if exclude_sample_ids:
        selector = ~np.isin(pairs["sample_ids"], sorted(exclude_sample_ids))
    X = pairs["X"][selector][:, mask]
    model = LogisticRegression(
        C=regularization,
        fit_intercept=False,
        solver="lbfgs",
        max_iter=3000,
        random_state=0,
    )
    model.fit(X, pairs["y"][selector], sample_weight=pairs["w"][selector])
    weights = np.zeros(len(RERANK_FEATURE_NAMES), dtype=np.float64)
    weights[list(mask)] = model.coef_[0]
    return weights


def static_eval(groups: list[dict], sample_ids: set[str], weights: np.ndarray) -> list[dict]:
    by_sample: dict[str, list[dict]] = defaultdict(list)
    scenarios: dict[str, str] = {}
    for group in groups:
        if group["sample_id"] in sample_ids:
            by_sample[group["sample_id"]].append(group)
            scenarios[group["sample_id"]] = group["scenario"]
    sessions: list[dict] = []
    for sample_id in sorted(sample_ids):
        hit_turn: int | None = None
        best_rank: int | None = None
        for group in sorted(by_sample.get(sample_id, []), key=lambda g: g["turn"]):
            if group.get("absent"):
                continue
            ranks = group["n_higher"] + tier_ranks(
                group["matrix"].astype(np.float64), group["pool_ranks"], weights
            )
            target_rank = int(ranks[group["target_index"]])
            if target_rank <= 10:
                hit_turn = int(group["turn"])
                best_rank = target_rank
                break
        sessions.append({
            "sample_id": sample_id,
            "scenario_type": scenarios.get(sample_id, "unknown"),
            "hit": hit_turn is not None,
            "first_hit_turn": hit_turn,
            "best_rank": best_rank,
            "reciprocal_rank": 0.0 if best_rank is None else 1.0 / best_rank,
        })
    return sessions


def evaluate_config(
    pairs: dict,
    groups: list[dict],
    mask: tuple[int, ...],
    regularization: float,
    fold_sets: list[set[str]],
    dev_ids: set[str],
    synthetic_dev_ids: set[str],
) -> dict:
    out_of_fold: list[dict] = []
    fold_metrics: list[dict] = []
    for fold_index, validation_ids in enumerate(fold_sets):
        weights = fit_weights(pairs, mask, regularization, exclude_sample_ids=validation_ids)
        sessions = static_eval(groups, validation_ids, weights)
        fold_metrics.append({"fold": fold_index, **technical_score(sessions)})
        out_of_fold.extend(sessions)
    oof = technical_score(out_of_fold)
    full_weights = fit_weights(pairs, mask, regularization)
    dev_sessions = static_eval(groups, synthetic_dev_ids, full_weights)
    synthetic_dev = technical_score(dev_sessions)
    selection = round(
        0.5 * oof["recommended_technical_score"]
        + 0.5 * synthetic_dev["recommended_technical_score"],
        6,
    )
    return {
        "mask": [RERANK_FEATURE_NAMES[i] for i in mask],
        "C": regularization,
        "public_oof": oof,
        "public_folds": fold_metrics,
        "synthetic_dev": synthetic_dev,
        "selection_score": selection,
        "weights": full_weights,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=Path("data/catalog.jsonl"))
    parser.add_argument("--dataset", type=Path, default=Path("data/public_set.jsonl"))
    parser.add_argument("--manifest", type=Path, default=Path("data/cp2_split.json"))
    parser.add_argument(
        "--synthetic-train", type=Path,
        default=Path("data/releases/cp4/synthetic_train.jsonl"),
    )
    parser.add_argument(
        "--synthetic-dev", type=Path,
        default=Path("data/releases/cp4/synthetic_dev.jsonl"),
    )
    parser.add_argument(
        "--groups-cache", type=Path,
        default=Path("data/releases/cp4/train_groups.pkl"),
    )
    parser.add_argument("--weights-output", type=Path, default=Path("starter/reranker_weights.json"))
    parser.add_argument("--report-output", type=Path, required=True)
    parser.add_argument("--pairs-per-group", type=int, default=60)
    parser.add_argument("--boundary-boost", type=float, default=3.0)
    parser.add_argument("--public-weight", type=float, default=20.0)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    dev_ids = {str(value) for value in manifest["dev_ids"]}
    fold_sets = [{str(value) for value in fold} for fold in manifest["folds"]]

    if args.groups_cache.exists():
        with args.groups_cache.open("rb") as handle:
            groups = pickle.load(handle)
        print(f"loaded {len(groups)} cached groups")
    else:
        _, categories, products = catalog_index(args.catalog)
        agent = Agent(args.catalog, load_reranker=False, use_fresh_tier_dominance=True)
        public_samples = [
            sample for sample in load_jsonl(args.dataset)
            if str(sample["sample_id"]) in dev_ids
        ]
        if len(public_samples) != len(dev_ids):
            raise ValueError("dev manifest and dataset do not match")
        groups = generate_groups(agent, public_samples, categories, products, "public")
        groups += generate_groups(
            agent, load_jsonl(args.synthetic_train), categories, products, "synthetic_train"
        )
        groups += generate_groups(
            agent, load_jsonl(args.synthetic_dev), categories, products, "synthetic_dev"
        )
        args.groups_cache.parent.mkdir(parents=True, exist_ok=True)
        with args.groups_cache.open("wb") as handle:
            pickle.dump(groups, handle, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"generated {len(groups)} groups")

    synthetic_dev_ids = {
        group["sample_id"] for group in groups if group["partition"] == "synthetic_dev"
    }
    train_groups = [
        group for group in groups if group["partition"] in ("public", "synthetic_train")
    ]
    coverage = sum(not group.get("absent") for group in train_groups) / max(1, len(train_groups))

    reference = np.asarray(Agent._load_reranker_weights() or [], dtype=np.float64)
    if reference.size != len(RERANK_FEATURE_NAMES):
        raise SystemExit("reference reranker weights are required for pair weighting")
    pairs = build_pairs(
        train_groups, reference, args.pairs_per_group,
        args.boundary_boost, args.public_weight,
    )
    print(f"pairs: {len(pairs['y'])} (coverage {coverage:.4f})")

    report: dict = {
        "protocol": "cp4-within-tier-mrr-weighted-v1",
        "manifest_sha256": hashlib.sha256(args.manifest.read_bytes()).hexdigest(),
        "group_count": len(groups),
        "train_group_coverage": round(coverage, 6),
        "pair_count": int(len(pairs["y"])),
        "pairs_per_group": args.pairs_per_group,
        "boundary_boost": args.boundary_boost,
        "public_weight": args.public_weight,
        "configs": [],
    }

    def run_config(mask: tuple[int, ...], regularization: float, label: str) -> dict:
        config = evaluate_config(
            pairs, groups, mask, regularization, fold_sets, dev_ids, synthetic_dev_ids
        )
        entry = {key: value for key, value in config.items() if key != "weights"}
        entry["label"] = label
        report["configs"].append(entry)
        print(json.dumps({
            "label": label,
            "C": regularization,
            "public_oof": config["public_oof"]["recommended_technical_score"],
            "synthetic_dev": config["synthetic_dev"]["recommended_technical_score"],
            "selection": config["selection_score"],
        }))
        return config

    # Stage 1: regularization on the 16 CP3 features.
    stage1 = [run_config(BASE_FEATURES, c, f"base16 C={c}") for c in C_GRID]
    best_base = max(stage1, key=lambda item: item["selection_score"])
    best_c = best_base["C"]

    # Stage 2: each candidate feature alone on top of the base set.
    extras = (
        "satisfied_constraints",
        "coarse_category_equality",
        "coarse_category_overlap",
        "max_matched_rarity",
        "unmatched_rarity",
        "price_presence_when_budget",
        "preference_tag_overlap",
    )
    stage2 = {}
    for name in extras:
        mask = BASE_FEATURES + (EXTRA_FEATURES[name],)
        stage2[name] = run_config(mask, best_c, f"base16+{name} C={best_c}")

    # Stage 3: combine every extra that beat the base selection score.
    winners = [
        name for name in extras
        if stage2[name]["selection_score"] > best_base["selection_score"]
    ]
    candidates = [best_base, *stage2.values()]
    if winners:
        mask = BASE_FEATURES + tuple(EXTRA_FEATURES[name] for name in winners)
        combo = run_config(mask, best_c, f"base16+{'+'.join(winners)} C={best_c}")
        candidates.append(combo)
        # Stage 4: re-tune C around the winner mask.
        for c in C_GRID:
            if c != best_c:
                candidates.append(run_config(mask, c, f"combo C={c}"))

    selected = max(candidates, key=lambda item: (
        item["selection_score"],
        item["public_oof"]["recommended_technical_score"],
        -item["C"],
    ))
    final_weights = selected["weights"]
    kept_names = selected["mask"]
    report["selected"] = {
        "mask": kept_names,
        "C": selected["C"],
        "selection_score": selected["selection_score"],
        "public_oof": selected["public_oof"],
        "synthetic_dev": selected["synthetic_dev"],
    }
    report["candidate_feature_outcomes"] = {
        name: {
            "kept": name in kept_names,
            "selection_score": stage2[name]["selection_score"],
            "delta_vs_base": round(
                stage2[name]["selection_score"] - best_base["selection_score"], 6
            ),
        }
        for name in extras
    }

    weights_payload = {
        "model": "pairwise_logistic_regression",
        "training_partition": "cp4_public_dev150_plus_synthetic_train3000",
        "protocol": report["protocol"],
        "manifest_sha256": report["manifest_sha256"],
        "regularization_C": selected["C"],
        "features": list(kept_names),
        "weights": {
            name: round(float(final_weights[EXTRA_FEATURES[name]]), 12)
            for name in kept_names
        },
    }
    report["final_weights"] = weights_payload["weights"]
    args.weights_output.parent.mkdir(parents=True, exist_ok=True)
    args.weights_output.write_text(json.dumps(weights_payload, indent=2) + "\n", encoding="utf-8")
    args.report_output.parent.mkdir(parents=True, exist_ok=True)
    args.report_output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"selected": report["selected"], "weights_output": str(args.weights_output)}, indent=2))


if __name__ == "__main__":
    main()
